### ISSUE TITLE
Function to plot 2d variogram with colours

### ISSUE THREAD

**Issue by rogerssam** [biometryhub/BiometryTraining#33]
Potential idea to explore

**Comment by snstats** [comment]
I have code that I have been using for a few years for this...

library(akima)
aa <- varioGram(dat.asr)
fld <- with(aa, interp(y = Row, x = Column, z = gamma))
gdat <- interp2xyz(fld, data.frame = TRUE)
ggplot(gdat, aes(x = x, y = y, z = z, fill = z)) +
geom_tile() +
coord_equal() +
geom_contour(color = "white", alpha = 0.5) +
scale_fill_distiller(palette = "Spectral", na.value = "white") +
theme_bw() + # to remove the grey background colour
xlab("Column") + # to change the x-axis label
ylab("Row") + # to change the y-axis label
labs(fill = "") # to remove the label from the legend

**Comment by rogerssam** [comment]
This is awesome, thanks @snstats!
We should add this function for cases when the variogram breaks.

**Comment by rogerssam** [comment]
Finally made some progress on this thanks to Russell! A question remains:

- Is this only relevant for asreml models, or do we want to handle other models?
