### ISSUE TITLE
new package name

### ISSUE THREAD

**Issue by emitanaka** [biometryhub/BiometryTraining#61]
I know you said that you already submitted to CRAN but if for some reason it doesn't go through, can I suggest a different name? I feel the name BiometryTraining doesn't suit the purpose (i.e. create helper functions for common tasks in design and analysis of agronomy experiments) and currently sounds like its only specific for training purposes. To match it's purpose, you could try to tangle words that align with the purpose, e.g. `agassist`, `agsupport`, etc. (Just a suggestion!)

**Comment by rogerssam** [comment]
New package biometryassist: https://github.com/biometryhub/biometryassist
